### ISSUE TITLE
ikona zmiany języka

### ISSUE THREAD

**Issue by stoooodnia** [UniversityOfGdanskProjects/plan_front#19]
zmienia się język, ale nie zmienia się ikona, w związku z tym kiedy jesteśmy w trybie j.angielskiego to nadal ikona mówi nam o możliwości zmiany na angielski a nie polski

głupotka ale do naprawy :)
<img width="658" alt="image" src="https://user-images.githubusercontent.com/106387832/203629350-f3592b38-ff81-4f39-8e41-1e0050af70d8.png">

**Comment by DawidRoszman** [comment]
fixed
